'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated. 
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On


Partial Public Class _Default
    
    '''<summary>
    '''dsGetWatchlistByID control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents dsGetWatchlistByID As Global.System.Web.UI.WebControls.SqlDataSource
    
    '''<summary>
    '''dsGetAllDataPointsForASingleStock control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents dsGetAllDataPointsForASingleStock As Global.System.Web.UI.WebControls.SqlDataSource
    
    '''<summary>
    '''dsGetWatchListsForAUser control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents dsGetWatchListsForAUser As Global.System.Web.UI.WebControls.SqlDataSource
    
    '''<summary>
    '''hfCurrentWatchlistID control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents hfCurrentWatchlistID As Global.System.Web.UI.WebControls.HiddenField
    
    '''<summary>
    '''lblListName control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblListName As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''btnDeleteWatchlist control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btnDeleteWatchlist As Global.System.Web.UI.WebControls.LinkButton
    
    '''<summary>
    '''lblSPXMarketPrice control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblSPXMarketPrice As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''lblSPXMarketPriceChange control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblSPXMarketPriceChange As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''upFundamentalDataPoints control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents upFundamentalDataPoints As Global.System.Web.UI.UpdatePanel
    
    '''<summary>
    '''lblStockSymbol control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblStockSymbol As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''rssWatchListRepeater control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents rssWatchListRepeater As Global.System.Web.UI.WebControls.Repeater
    
    '''<summary>
    '''fvFundamentalDataPoints control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents fvFundamentalDataPoints As Global.System.Web.UI.WebControls.FormView
End Class
